[package]
name = "casscf-tete"
version = "0.1.0"
authors = ["Cyrille Lavigne <cyrille.lavigne@mail.utoronto.ca>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
# optimized for smaller binaries
